---

############################
##### Daemon - Node.js #####
############################

- name: Ensure Directory - ~/logs/
  file: path=/home/{{ ansible_ssh_user }}/logs state=directory owner={{ ansible_ssh_user }} group=sudo mode=0755
  become: yes

- name: Ensure Directory - ~/pids/
  file: path=/home/{{ ansible_ssh_user }}/pids state=directory owner={{ ansible_ssh_user }} group=sudo mode=0755
  become: yes

- name: Copy Node Upstart Daemon Service
  template: src=daemon.nodejs.conf.j2 dest=/etc/init/{{ daemon_name }}.conf mode=0644
  become: yes
  notify: Restart Daemon

- name: Ensure Node Daemon is started
  become: yes
  service: name={{ daemon_name }} state=started enabled=yes
